export const LOADING_TRUE = "LOADING_TRUE";
export const LOADING_FALSE = "LOADING_FALSE";


export const GET_TRENDING = "GET_TRENDING";
export const GET_SINGLE_CINEMA = "GET_SINGLE_CINEMA";
export const GET_SINGLE_CINEMA_VIDEO = "GET_SINGLE_CINEMA_VIDEO";
export const GET_SINGLE_CINEMA_CREDITS = "GET_SINGLE_CINEMA_CREDITS";

